Lab2
Vsevolond/FormalLanguage_Labs pull request #3
Opened 2023-10-14 14:14 UTC by Vsevolond

2023-10-19 19:33 UTC, TonitaN requested changes
Резюме: нужно доразобраться с ассоциативными операциями и входным синтаксисом. Потому что тут уже не регулярное преобразование синтаксиса.
Пример регулярок в правильном синтаксисе:
```
a*a*a*b
(a*)*(a*)
((a*)a*)
```

2023-10-19 19:33 UTC, TonitaN commented on Labs/lab2/fuzz/functions.py
> +        right_leaves = letters_cnt // 2
Интересно, кто первый придумал делать идеально сбалансированные деревья в рандомных регулярках? У трёх первых сдающих групп всё было в порядке...

2023-10-19 19:33 UTC, TonitaN commented on Labs/lab2/fuzz/functions.py
> +            stars = 0
А не приведёт ли это к сбою в подсчёте звёздной высоты?
Например, в такой регулярке:
```
(a|(b|c*))*
```

2023-10-19 19:33 UTC, TonitaN commented on Labs/lab2/core/main.swift
> +                    ) { // xx*|e -> x*, x*x|e -> x*
За дополнительные упрощения - плюс в карму! Но их можно было сделать меньше, с учётом ACI, который всегда будет располагать эпсилон строго с одной стороны от итерации.

2023-10-19 19:33 UTC, TonitaN commented on Labs/lab2/core/main.swift
> +        let perform: () -> Void = {
Вот в парсере проблема с небинарностью, нужно аккуратно с этим разобраться.

2023-10-21 10:52 UTC, Vsevolond commented on Labs/lab2/core/main.swift
> +                    ) { // xx*|e -> x*, x*x|e -> x*
сократил проверки

2023-10-21 10:55 UTC, Vsevolond commented on Labs/lab2/core/main.swift
> +        let perform: () -> Void = {
поправил парсер

2023-10-22 20:57 UTC, TonitaN commented
Строго говоря, это уже *далеко* не только SSNF, но получилось даже интереснее. Зачёт!

2023-10-22 20:59 UTC, Vsevolond commented
Спасибо!

Вс, 22 окт. 2023 г. в 23:58, Antonina Nepeivoda ***@***.***>:

> Строго говоря, это уже *далеко* не только SSNF, но получилось даже
> интереснее. Зачёт!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vsevolond/FormalLanguage_Labs/pull/3#issuecomment-1774197155>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVRR7B2ORX2B6CRAGBVLTK3YAWCFZAVCNFSM6AAAAAA6AJESMGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZUGE4TOMJVGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-23 09:29 UTC, merged